name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Cosmopolitan Python
        run: |
          wget https://cosmo.zip/pub/cosmos/bin/python -O python.exe
          chmod +x python.exe

          PY_VERSION=$(./python.exe -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
          echo "py_version=$PY_VERSION" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.py_version }}

      - name: Install and bundle dependencies
        run: |
          python -m pip wheel --no-deps .

          mkdir target
          pip install --target=./target --implementation py --platform any --abi none --only-binary=:all: ./termnotes-*.whl

          folders=$(ls target)

          for folder in $folders; do
            python scripts/add_to_zip.py ./target/"$folder" ./python.exe Lib/site-packages/"$folder"
          done

          zip -urj python.exe scripts/.args

      - name: Rename
        run: mv python.exe termnotes.exe

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: termnotes-executable
          path: termnotes.exe
