name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get Cosmopolitan Python
        run: |
          wget https://cosmo.zip/pub/cosmos/bin/python -O python.exe
          chmod +x python.exe

          PY_VERSION=$(./python.exe -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
          echo "py_version=$PY_VERSION" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.py_version }}

      - name: Install and bundle dependencies
        run: |
          python -m pip wheel .
          python -m venv venv
          source venv/bin/activate
          pip install termnotes*.whl

          MODULES=$(pip list --format=freeze | cut -d= -f1)

          for MODULE in $MODULES; do
            if [ "$MODULE" = "pip" ]; then
              continue
            fi

            MODULE_PATH=$(python -c "import os, $MODULE; print(os.path.dirname($MODULE.__file__))")
            python scripts/add_dir_into_zip.py "$MODULE_PATH" ./python.exe Lib/site-packages/"$MODULE"

            DISTINFO_FOLDER_PATH=$(echo $MODULE_PATH*.dist-info)
            python scripts/add_dir_into_zip.py "$DISTINFO_FOLDER_PATH" ./python.exe Lib/site-packages/$(basename "$DISTINFO_FOLDER_PATH")
          done

          zip -urj python.exe scripts/.args

      - name: Rename
        run: mv python.exe termnotes.exe

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: termnotes-executable
          path: termnotes.exe
